sonar.projectKey=VHIANCEERICH_scholar_php
sonar.organization=VHIANCEERICH
sonar.projectName=scholar_php
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.inclusions=**/*.php
sonar.exclusions=uploads/**,**/*.bak_*,**/vendor/**,.github/**,nginx/**
